### PR TITLE
Add Spring Security

### LINKED ISSUE #70: Add Security

### PR DESCRIPTION
**Pull request by Vimbayinashe**
- Closes #70 
- adds spring security
- adds some default `html` files which will be updated in issue #75

### CODE REVIEW

**Comment by Ahsanadam** [comment]
I have review this and I was just curious why there is a lot of files that maybe has to do with queue rather than the security that we went through on the Spring security lectures by Pontus. Are all the files that has been changed on this pull request related to security?

**Comment by Ahsanadam** [comment]
The security part looks great, but we need to distiguish the parts that has to with queue in another pull request maybe ?

**Comment by Vimbayinashe** [comment]
Because there has been considerable time between pull requests and when they are merged, I have continued to build upon unmerged pull requests in order to meet our deadline. I suggest that the pull requests I have submitted are reviewed from the earliest pull request, #67, and working upwards.

**Review by Ahsanadam — APPROVED** [review]
Understandable. The security part looks good !

**Pull request merged**
