### PR TITLE
Add endpoints for Author, BookFormat & Genre

### PR DESCRIPTION
**Pull request by Ahsanadam**

### CODE REVIEW

**Comment by Vimbayinashe** [comment]
Great work Ahsan!

We need to return only DTOs instead of entities (according to the project requirements). I suggest that we use modelMapper to map entities into DTOs in the service class. 
We also need to handle Optionals so that we either return a DTO or the user receives an error message.


An example of how findGenreById in GenreService class _(this is just an example and I have not tested this code):_
```
public Genre findGenreById(Long id){
   GenreEntity genreEntity = genreRepository.findById(id).orElseThrow(() -> new IdNotFoundException("genre", id));
   return modelMapper.map(genreEntity, Genre.class);
}
```

**Comment by Ahsanadam** [comment]
Thank you , you can check the changes that I have made after your suggestions. Done for reviewing again.

**Review by ToniKaru — CHANGES_REQUESTED** [review]
* Add no-argument constructors to both BookFormat and Author dtos.
(Receiving a error message when trying to use all endpoints in BookFormatController and AuthorController in Insomnia... 
"error": "Internal Server Error",
"message": "ModelMapper mapping errors:\n\n1) Failed to instantiate instance of destination se.iths.librarysystem.dto.BookFormat. Ensure that se.iths.librarysystem.dto.BookFormat has a non-private no-argument constructor.\n\n1 error")

**Review by ToniKaru — APPROVED** [review]
All the endpoints look and work great. :)

**Comment by ToniKaru** [comment]
This will also close issue #10.

**Pull request merged**
