### PR TITLE
Add relations between the entities, related to issue 10 

### PR DESCRIPTION
**Pull request by Ahsanadam**

### CODE REVIEW

**Review by ToniKaru — CHANGES_REQUESTED** [review]
Two quite notes:
1. Looks like the new lists need getters, adders and removers. Similar to:     
public List<UserEntity> getUsers() {  return Collections.unmodifiableList(users);    }
public void addUser(UserEntity user) { users.add(user); }
public void removeUser(UserEntity user) { users.remove(user); }
2. Some of the BookEntity new lists are missing private access modifier.

**Comment by Ahsanadam** [comment]
I made the lists as private access but where do I find public List getUsers() { return Collections.unmodifiableList(users); }
public void addUser(UserEntity user) { users.add(user); }
public void removeUser(UserEntity user) { users.remove(user); },

On which class can I find this? I have looked on my local main branch even after making a git pull and I cannot find it ?

**Comment by Ahsanadam** [comment]
I have done the changes that you have requested . Hopefully it should be implemented now.

**Comment by Vimbayinashe** [comment]
Great work Ahsan!

It looks like there are a few getters, setters and adders still missing:

Lists requiring getters, setters & adders:
1. enrolledBooks  in AuthorEntity, 
2. authors in BookEntity

Fields requiring getters & setters
1. bookEntity2 in BookFormatEntity
2. bookEntity2 in GenreEntity

**Comment by Ahsanadam** [comment]
I have done the changes that were requested now, its ready to be reviewed again.

**Review by ToniKaru — CHANGES_REQUESTED** [review]
Change relationship between entities as follows:
in BookEntity change genreEntities to ManytoOne
in GenreEntity change bookEntity2 to OneToMany
in BookEnity change bookFormats to Many to Many
in BookFormat change bookEntity2 to ManyToMany

**Comment by Vimbayinashe** [comment]
Looks great!

**Review by Vimbayinashe — APPROVED** [review]

**Review by Vimbayinashe — APPROVED** [review]

**Review by Vimbayinashe — APPROVED** [review]

**Review by ToniKaru — APPROVED** [review]
The changes look good

**Pull request merged**
